### ISSUE TITLE
Pixels app TODO list

### ISSUE THREAD

**Issue by obasille** [GameWithPixels/pixels-js#53]
- [ ] useDisclose() => rename returned params 
- [ ] HomeScreen: always show paired dice, duplicate dice scan bug 
- [ ] FastXXX => Just XXX, add w100, h100, full & center shortands, remove w & h 
- [ ] ActionsheetList => ActionSheetList 
- [ ] Remove chevrons and Frame 
- [ ] IColor => ColorValue ? 
- [ ] ColorWheel + SelectColorModal color param and selection 
- [ ] FastBox => StaticBox, add "center" prop 
- [ ] Check profile hash before playing clip/text 
- [ ] EditCondition flags should be array of keys (strings) 
- [ ] Add usePixelValue remoteAction ? 
- [ ] Move json convert function into object in export (from loadAppDataSet)
